fix release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -3,8 +3,8 @@ name: Release
 # Only run on new tags starting with `v`
 on:
   push:
-    tags:
-      - 'v*'
+    # tags:
+    #   - 'v*'
 
 jobs:
   build:
@@ -19,26 +19,43 @@ jobs:
       with:
         python-version: '3.11'
 
+    - uses: actions/setup-node@v3
+      with:
+        node-version: "20"
+
+    - name: Install JS dependencies
+      run: |
+        npm install
+
+    - name: Build JS bundle
+      run: |
+        npm run build
+
     - name: Build dist
       run: |
         python -m pip install -U build
         python -m build
 
+    - name: Ensure JS files included
+      run: |
+        # If no files with path lonboard/static, fail
+        unzip -l dist/*.whl | grep "lonboard/static" || exit 1
+
     - uses: actions/upload-artifact@v3
       with:
         path: ./dist/
 
-  upload_pypi:
-    needs: [build]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/download-artifact@v3
-        with:
-          name: artifact
-          path: dist
+  # upload_pypi:
+  #   needs: [build]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/download-artifact@v3
+  #       with:
+  #         name: artifact
+  #         path: dist
 
-      - uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          user: __token__
-          password: ${{ secrets.PYPI_API_TOKEN }}
-          # To test: repository_url: https://test.pypi.org/legacy/
+  #     - uses: pypa/gh-action-pypi-publish@release/v1
+  #       with:
+  #         user: __token__
+  #         password: ${{ secrets.PYPI_API_TOKEN }}
+  #         # To test: repository_url: https://test.pypi.org/legacy/
