fix release (#100)
* fix release

* restore comments

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -19,10 +19,27 @@ jobs:
       with:
         python-version: '3.11'
 
+    - uses: actions/setup-node@v3
+      with:
+        node-version: "20"
+
+    - name: Install JS dependencies
+      run: |
+        npm install
+
+    - name: Build JS bundle
+      run: |
+        npm run build
+
     - name: Build dist
       run: |
         python -m pip install -U build
         python -m build
+
+    - name: Ensure JS files included
+      run: |
+        # If no files with path lonboard/static, fail
+        unzip -l dist/*.whl | grep "lonboard/static" || exit 1
 
     - uses: actions/upload-artifact@v3
       with:
